### PR TITLE
Add obligatory citation

### PR DESCRIPTION
**Pull request by rugk**
If you already name it as such, this is really needed… 😜😇

### CODE REVIEW

**Review by flotwig — APPROVED** [review]
:laughing:

**Comment by rugk** [comment]
Awesome! Would you like to tag this as aligable for Hacktoberfest? This would be really nice. 😃 

[Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/) – a project promoting open source contributions – is running this month.

As [they have changed the rules recenty](https://dev.to/devteam/hacktoberfest-etiquette-for-contributors-ec6) you do now have to tag your repository/repositories (=set a GItHub topic) if you want to have participated in this with the tag `hacktoberfest`.
AFAIK you can alternatively also [tag single PRs with `hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/details#details) to mark them as a valid PR. (Otherwise all merged or positively reviewed PRs count.)

**Comment by flotwig** [comment]
tagged :)

**Comment by rugk** [comment]
Thanks. 😊

**Pull request merged**
